### ISSUE TITLE
Which severity level of data corruption do you use in the experiments?

### ISSUE THREAD

**Issue by auniquesun** [jmiemirza/MATE#2]
Thanks for sharing the paper and code.

I am confusing which severity level of data corruption do you use for ModelNet40-C, ShapeNet-C, ScanObjectNN-C, since there are 5 severity levels, from 1 to 5.

Looking forward to your reply. Thanks

**Comment by jmiemirza** [comment]
hi, thank you for your interest. we evaluated with the highest severity in the paper. 

best, mirza.

**Comment by auniquesun** [comment]
> hi, thank you for your interest. we evaluated with the highest severity in the paper.
> 
> best, mirza.

Thanks for your reply.
